namespace Techsola.EmbedDependencies.ILAsmSyntax
{
    internal enum SyntaxKind
    {
        Error,
        End,
        ExclamationToken,
        DoubleExclamationToken,
        AmpersandToken,
        AsteriskToken,
        OpenAngleToken,
        CloseAngleToken,
        OpenSquareToken,
        CloseSquareToken,
        OpenParenToken,
        CloseParenToken,
        CommaToken,
        DotToken,
        EllipsisToken,
        SlashToken,
        DoubleColonToken,
        NumericLiteralToken,
        StringLiteralToken,

        // If keyword entries change, update ILAsmLexer.KeywordsStartingWithPossibleIdentifierChar.
        BoolKeyword,
        CharKeyword,
        ClassKeyword,
        DefaultKeyword,
        DotCctorKeyword,
        DotCtorKeyword,
        DotModuleKeyword,
        ExplicitKeyword,
        Float32Keyword,
        Float64Keyword,
        InstanceKeyword,
        IntKeyword,
        Int8Keyword,
        Int16Keyword,
        Int32Keyword,
        Int64Keyword,
        MethodKeyword,
        ModoptKeyword,
        ModreqKeyword,
        NativeKeyword,
        ObjectKeyword,
        PinnedKeyword,
        StringKeyword,
        TypedReferenceKeyword,
        UnmanagedKeyword,
        UnsignedKeyword,
        ValueTypeKeyword,
        VarargKeyword,
        VoidKeyword,

        Identifier
    }
}
